### ISSUE TITLE
Fjern produksjon av `*_REASONED`

### ISSUE THREAD

**Issue by NilsOveTen** [Informasjonsforvaltning/fdk-kafka-event-publisher#103]
- Fjern lytting etter rabbit-rapportene om gjennomført reasoning, og medfølgende produksjon av `*_REASONED`-meldinger
- #109

må skje i sammenheng med med https://github.com/orgs/Informasjonsforvaltning/projects/9/views/31?pane=issue&itemId=50082401

**Comment by terjesyl** [comment]
Setter i In review til det er prodsatt (planlagt torsdag 30. mai)
